from typing import Any

from django.forms.models import BaseInlineFormSet

class StockRecordFormSet(BaseInlineFormSet):
    user: Any
    require_user_stockrecord: bool
    product_class: Any
    def __init__(self, product_class: Any, user: Any, *args: Any, **kwargs: Any) -> None: ...
    def set_initial_data(self) -> None: ...
    def clean(self) -> None: ...

class ProductCategoryFormSet(BaseInlineFormSet):
    def __init__(self, product_class: Any, user: Any, *args: Any, **kwargs: Any) -> None: ...
    def clean(self) -> None: ...
    def get_num_categories(self) -> int: ...

class ProductImageFormSet(BaseInlineFormSet):
    def __init__(self, product_class: Any, user: Any, *args: Any, **kwargs: Any) -> None: ...

class ProductRecommendationFormSet(BaseInlineFormSet):
    def __init__(self, product_class: Any, user: Any, *args: Any, **kwargs: Any) -> None: ...

ProductAttributesFormSet: type[BaseInlineFormSet]
AttributeOptionFormSet: type[BaseInlineFormSet]
