from typing import Any

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views import generic
from django_tables2 import SingleTableMixin, SingleTableView
from oscar.apps.dashboard.catalogue.mixins import PartnerProductFilterMixin, PublicVisibilityUpdateMixin
from oscar.apps.dashboard.views import PopUpWindowCreateMixin, PopUpWindowDeleteMixin, PopUpWindowUpdateMixin
from oscar.views.generic import ObjectLookupView

class ProductListView(PublicVisibilityUpdateMixin, PartnerProductFilterMixin, SingleTableView):
    template_name: str
    form_class: type
    productclass_form_class: type
    table_class: type
    context_table_name: str
    form: Any
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_description(self, form: Any) -> str: ...
    def get_table(self, **kwargs: Any) -> Any: ...
    def get_table_pagination(self, table: Any) -> dict[str, int]: ...
    def get_queryset(self) -> QuerySet[Any]: ...
    def apply_search(self, queryset: QuerySet[Any]) -> QuerySet[Any]: ...

class ProductCreateRedirectView(generic.RedirectView):
    permanent: bool
    productclass_form_class: type
    def get_product_create_url(self, product_class: Any) -> str: ...
    def get_invalid_product_class_url(self) -> str: ...
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str: ...

class ProductCreateUpdateView(PartnerProductFilterMixin, generic.UpdateView):
    template_name: str
    context_object_name: str
    form_class: type
    category_formset: type
    image_formset: type
    recommendations_formset: type
    stockrecord_formset: type
    creating: bool
    parent: Any
    product_class: Any
    formsets: dict[str, type]
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def check_objects_or_redirect(self) -> HttpResponse | None: ...
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_page_title(self) -> str: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def process_all_forms(self, form: Any) -> HttpResponse: ...
    def clean(self, form: Any, formsets: dict[str, Any]) -> bool: ...
    def forms_valid(self, form: Any, formsets: dict[str, Any]) -> HttpResponseRedirect: ...
    def handle_adding_child(self, parent: Any) -> None: ...
    def forms_invalid(self, form: Any, formsets: dict[str, Any]) -> HttpResponse: ...
    def get_url_with_querystring(self, url: str) -> str: ...
    def get_success_url(self) -> str: ...

class ProductDeleteView(PartnerProductFilterMixin, generic.DeleteView):
    template_name: str
    context_object_name: str
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def delete(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponseRedirect: ...
    def handle_deleting_last_child(self, parent: Any) -> None: ...
    def get_success_url(self) -> str: ...

class StockAlertListView(generic.ListView):
    template_name: str
    context_object_name: str
    paginate_by: int
    form: Any
    description: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_queryset(self) -> QuerySet[Any]: ...

class CategoryListView(PublicVisibilityUpdateMixin, SingleTableView):
    template_name: str
    table_class: type
    form_class: type
    context_table_name: str
    form: Any
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

class CategoryDetailListView(PublicVisibilityUpdateMixin, SingleTableMixin, generic.DetailView):
    template_name: str
    context_object_name: str
    table_class: type
    context_table_name: str
    def get_table_data(self) -> QuerySet[Any]: ...
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

class CategoryListMixin:
    def get_success_url(self) -> str: ...

class CategoryCreateView(CategoryListMixin, generic.CreateView):
    template_name: str
    form_class: type
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...
    def get_initial(self) -> dict[str, Any]: ...

class CategoryUpdateView(CategoryListMixin, generic.UpdateView):
    template_name: str
    form_class: type
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class CategoryDeleteView(CategoryListMixin, generic.DeleteView):
    template_name: str
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class ProductLookupView(ObjectLookupView):
    def get_queryset(self) -> QuerySet[Any]: ...
    def lookup_filter(self, qs: QuerySet[Any], term: str) -> QuerySet[Any]: ...

class ProductClassCreateUpdateView(generic.UpdateView):
    template_name: str
    form_class: type
    product_attributes_formset: type
    creating: bool
    def process_all_forms(self, form: Any) -> HttpResponse: ...
    def forms_valid(self, form: Any, attributes_formset: Any) -> HttpResponseRedirect: ...
    def forms_invalid(self, form: Any, attributes_formset: Any) -> HttpResponse: ...
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

class ProductClassCreateView(ProductClassCreateUpdateView):
    creating: bool
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> None: ...
    def get_title(self) -> str: ...
    def get_success_url(self) -> str: ...

class ProductClassUpdateView(ProductClassCreateUpdateView):
    creating: bool
    def get_title(self) -> str: ...
    def get_success_url(self) -> str: ...
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...

class ProductClassListView(generic.ListView):
    template_name: str
    context_object_name: str
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

class ProductClassDeleteView(generic.DeleteView):
    template_name: str
    form_class: type
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class AttributeOptionGroupCreateUpdateView(generic.UpdateView):
    template_name: str
    form_class: type
    attribute_option_formset: type
    creating: bool
    def process_all_forms(self, form: Any) -> HttpResponse: ...
    def forms_valid(self, form: Any, attribute_option_formset: Any) -> HttpResponse: ...
    def forms_invalid(self, form: Any, attribute_option_formset: Any) -> HttpResponse: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_url_with_querystring(self, url: str) -> str: ...

class AttributeOptionGroupCreateView(PopUpWindowCreateMixin, AttributeOptionGroupCreateUpdateView):
    creating: bool
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> None: ...
    def get_title(self) -> str: ...
    def get_success_url(self) -> str: ...

class AttributeOptionGroupUpdateView(PopUpWindowUpdateMixin, AttributeOptionGroupCreateUpdateView):
    creating: bool
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_title(self) -> str: ...
    def get_success_url(self) -> str: ...

class AttributeOptionGroupListView(SingleTableView):
    template_name: str
    table_class: type
    context_table_name: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class AttributeOptionGroupDeleteView(PopUpWindowDeleteMixin, generic.DeleteView):
    template_name: str
    form_class: type
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_url_with_querystring(self, url: str) -> str: ...
    def get_success_url(self) -> str: ...

class OptionListView(SingleTableView):
    template_name: str
    table_class: type
    context_table_name: str

class OptionCreateUpdateView(generic.UpdateView):
    template_name: str
    form_class: type
    creating: bool
    def form_valid(self, form: Any) -> HttpResponse: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def form_invalid(self, form: Any) -> HttpResponse: ...

class OptionCreateView(PopUpWindowCreateMixin, OptionCreateUpdateView):
    creating: bool
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> None: ...
    def get_title(self) -> str: ...
    def get_success_url(self) -> str: ...

class OptionUpdateView(PopUpWindowUpdateMixin, OptionCreateUpdateView):
    creating: bool
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_title(self) -> str: ...
    def get_success_url(self) -> str: ...

class OptionDeleteView(PopUpWindowDeleteMixin, generic.DeleteView):
    template_name: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...
