from typing import Any
import logging

from django.core.mail import EmailMessage, EmailMultiAlternatives
from oscar.apps.communication.abstract_models import AbstractEmail

class Dispatcher:
    logger: logging.Logger
    mail_connection: Any

    def __init__(self, logger: logging.Logger | None = ..., mail_connection: Any = ...) -> None: ...
    def dispatch_direct_messages(
        self, recipient_email: str, messages: dict[str, str], attachments: list[Any] | None = ...
    ) -> EmailMessage | EmailMultiAlternatives | None: ...
    def dispatch_anonymous_messages(
        self, email: str, messages: dict[str, str], attachments: list[Any] | None = ...
    ) -> dict[str, Any]: ...
    def dispatch_user_messages(
        self, user: Any, messages: dict[str, str], attachments: list[Any] | None = ...
    ) -> dict[str, Any]: ...
    def notify_user(self, user: Any, subject: str, **kwargs: Any) -> None: ...
    def notify_users(self, users: Any, subject: str, **kwargs: Any) -> None: ...
    def create_email(
        self, user: Any, messages: dict[str, str], email: EmailMessage | EmailMultiAlternatives | None
    ) -> AbstractEmail | None: ...
    def send_user_email_messages(
        self, user: Any, messages: dict[str, str], attachments: list[Any] | None = ...
    ) -> EmailMessage | EmailMultiAlternatives | None: ...
    def send_email_messages(
        self,
        recipient_email: str,
        messages: dict[str, str],
        from_email: str | None = ...,
        attachments: list[Any] | None = ...,
    ) -> EmailMessage | EmailMultiAlternatives: ...
    def send_text_message(self, user: Any, event_type: Any) -> None: ...
    def prepare_attachments(self, attachments: list[Any] | None) -> tuple[list[Any], list[str]]: ...
    def get_base_context(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_messages(self, event_code: str, extra_context: dict[str, Any] | None = ...) -> dict[str, str]: ...
