from oscar.apps.analytics.abstract_models import (
    AbstractProductRecord,
    AbstractUserProductView,
    AbstractUserRecord,
    AbstractUserSearch,
)

class ProductRecord(AbstractProductRecord): ...
class UserRecord(AbstractUserRecord): ...
class UserProductView(AbstractUserProductView): ...
class UserSearch(AbstractUserSearch): ...
