from typing import Any

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View
from oscar.views.generic import BulkEditMixin

class RangeListView(ListView):
    context_object_name: str
    template_name: str
    paginate_by: int
    def get_queryset(self) -> QuerySet[Any]: ...

class RangeCreateView(CreateView):
    template_name: str
    form_class: type
    def get_success_url(self) -> str: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class RangeUpdateView(UpdateView):
    template_name: str
    form_class: type
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_success_url(self) -> str: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class RangeDeleteView(DeleteView):
    template_name: str
    context_object_name: str
    def get_success_url(self) -> str: ...

class RangeProductListView(BulkEditMixin, ListView):
    template_name: str
    context_object_name: str
    actions: tuple[str, ...]
    form_class: type
    paginate_by: int
    upload_type: str
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_product_range(self) -> Any: ...
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def remove_selected_products(self, request: HttpRequest, products: QuerySet[Any]) -> HttpResponse: ...
    def add_products(self, request: HttpRequest) -> HttpResponse: ...
    def add_excluded_products(self, request: HttpRequest) -> HttpResponse: ...
    def remove_excluded_products(self, request: HttpRequest) -> HttpResponse: ...
    def handle_query_products(self, request: HttpRequest, product_range: Any, form: Any) -> None: ...
    def handle_file_products(self, request: HttpRequest, product_range: Any, form: Any) -> None: ...
    def create_upload_object(self, request: HttpRequest, product_range: Any, f: Any, upload_type: str) -> Any: ...
    def check_imported_products_sku_duplicates(self, request: HttpRequest, queryset: QuerySet[Any]) -> None: ...

class RangeReorderView(View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponse: ...
