from typing import Any

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.views import generic

class PartnerListView(generic.ListView):
    context_object_name: str
    template_name: str
    form_class: type
    description: str
    is_filtered: bool
    form: Any
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class PartnerCreateView(generic.CreateView):
    template_name: str
    form_class: type
    success_url: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class PartnerManageView(generic.UpdateView):
    template_name: str
    form_class: type
    success_url: str
    partner: Any
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_initial(self) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...

class PartnerDeleteView(generic.DeleteView):
    template_name: str
    def get_success_url(self) -> str: ...

class PartnerUserCreateView(generic.CreateView):
    template_name: str
    form_class: type
    partner: Any
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class PartnerUserSelectView(generic.ListView):
    template_name: str
    form_class: type
    context_object_name: str
    partner: Any
    form: Any
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_queryset(self) -> QuerySet[Any]: ...

class PartnerUserLinkView(generic.View):
    def get(self, request: HttpRequest, user_pk: int, partner_pk: int) -> HttpResponse: ...
    def post(self, request: HttpRequest, user_pk: int, partner_pk: int) -> HttpResponse: ...
    def link_user(self, user: Any, partner: Any) -> bool: ...

class PartnerUserUnlinkView(generic.View):
    def unlink_user(self, user: Any, partner: Any) -> bool: ...
    def post(self, request: HttpRequest, user_pk: int, partner_pk: int) -> HttpResponse: ...

class PartnerUserUpdateView(generic.UpdateView):
    template_name: str
    form_class: type
    partner: Any
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...
