from oscar.apps.address.abstract_models import AbstractPartnerAddress
from oscar.apps.partner.abstract_models import AbstractPartner, AbstractStockAlert, AbstractStockRecord

class Partner(AbstractPartner): ...
class PartnerAddress(AbstractPartnerAddress): ...
class StockRecord(AbstractStockRecord): ...
class StockAlert(AbstractStockAlert): ...
