from decimal import Decimal
from typing import Any, ClassVar, NamedTuple

from oscar.apps.partner.availability import Base as AvailabilityBase
from oscar.apps.partner.prices import Base as PriceBase

class PurchaseInfo(NamedTuple):
    price: PriceBase
    availability: AvailabilityBase
    stockrecord: Any

class Selector:
    def strategy(self, request: Any | None = ..., user: Any | None = ..., **kwargs: Any) -> Default: ...

class Base:
    request: Any | None
    user: Any | None

    def __init__(self, request: Any | None = ...) -> None: ...
    def fetch_for_product(self, product: Any, stockrecord: Any | None = ...) -> PurchaseInfo: ...
    def fetch_for_parent(self, product: Any) -> PurchaseInfo: ...
    def fetch_for_line(self, line: Any, stockrecord: Any | None = ...) -> PurchaseInfo: ...

class Structured(Base):
    def fetch_for_product(self, product: Any, stockrecord: Any | None = ...) -> PurchaseInfo: ...
    def fetch_for_parent(self, product: Any) -> PurchaseInfo: ...
    def select_stockrecord(self, product: Any) -> Any: ...
    def select_children_stockrecords(self, product: Any) -> list[tuple[Any, Any]]: ...
    def pricing_policy(self, product: Any, stockrecord: Any) -> PriceBase: ...
    def parent_pricing_policy(self, product: Any, children_stock: list[tuple[Any, Any]]) -> PriceBase: ...
    def availability_policy(self, product: Any, stockrecord: Any) -> AvailabilityBase: ...
    def parent_availability_policy(self, product: Any, children_stock: list[tuple[Any, Any]]) -> AvailabilityBase: ...

class UseFirstStockRecord:
    def select_stockrecord(self, product: Any) -> Any | None: ...

class StockRequired:
    def availability_policy(self, product: Any, stockrecord: Any) -> AvailabilityBase: ...
    def parent_availability_policy(self, product: Any, children_stock: list[tuple[Any, Any]]) -> AvailabilityBase: ...

class NoTax:
    def pricing_policy(self, product: Any, stockrecord: Any) -> PriceBase: ...
    def parent_pricing_policy(self, product: Any, children_stock: list[tuple[Any, Any]]) -> PriceBase: ...

class FixedRateTax:
    rate: ClassVar[Decimal]
    exponent: ClassVar[Decimal]

    def pricing_policy(self, product: Any, stockrecord: Any) -> PriceBase: ...
    def parent_pricing_policy(self, product: Any, children_stock: list[tuple[Any, Any]]) -> PriceBase: ...
    def get_rate(self, product: Any, stockrecord: Any) -> Decimal: ...
    def get_exponent(self, stockrecord: Any) -> Decimal: ...

class DeferredTax:
    def pricing_policy(self, product: Any, stockrecord: Any) -> PriceBase: ...
    def parent_pricing_policy(self, product: Any, children_stock: list[tuple[Any, Any]]) -> PriceBase: ...

class Default(UseFirstStockRecord, StockRequired, NoTax, Structured): ...

class UK(UseFirstStockRecord, StockRequired, FixedRateTax, Structured):
    rate: ClassVar[Decimal]

class US(UseFirstStockRecord, StockRequired, DeferredTax, Structured): ...
