from typing import Any

OSCAR_SHOP_NAME: str
OSCAR_SHOP_TAGLINE: str
OSCAR_HOMEPAGE: str

# Dynamic class loading
OSCAR_DYNAMIC_CLASS_LOADER: str

# Basket settings
OSCAR_BASKET_COOKIE_LIFETIME: int
OSCAR_BASKET_COOKIE_OPEN: str
OSCAR_BASKET_COOKIE_SECURE: bool
OSCAR_MAX_BASKET_QUANTITY_THRESHOLD: int

# Recently-viewed products
OSCAR_RECENTLY_VIEWED_COOKIE_LIFETIME: int
OSCAR_RECENTLY_VIEWED_COOKIE_NAME: str
OSCAR_RECENTLY_VIEWED_COOKIE_SECURE: bool
OSCAR_RECENTLY_VIEWED_PRODUCTS: int

# Currency
OSCAR_DEFAULT_CURRENCY: str

# Paths
OSCAR_IMAGE_FOLDER: str
OSCAR_DELETE_IMAGE_FILES: bool
OSCAR_MISSING_IMAGE_URL: str

# Address settings
OSCAR_REQUIRED_ADDRESS_FIELDS: tuple[str, ...]

# Pagination settings
OSCAR_OFFERS_PER_PAGE: int
OSCAR_PRODUCTS_PER_PAGE: int
OSCAR_REVIEWS_PER_PAGE: int
OSCAR_NOTIFICATIONS_PER_PAGE: int
OSCAR_EMAILS_PER_PAGE: int
OSCAR_ORDERS_PER_PAGE: int
OSCAR_ADDRESSES_PER_PAGE: int
OSCAR_STOCK_ALERTS_PER_PAGE: int
OSCAR_DASHBOARD_ITEMS_PER_PAGE: int

# Checkout
OSCAR_ALLOW_ANON_CHECKOUT: bool

# Reviews
OSCAR_ALLOW_ANON_REVIEWS: bool
OSCAR_MODERATE_REVIEWS: bool

# Accounts
OSCAR_ACCOUNTS_REDIRECT_URL: str

# Alerts
OSCAR_EAGER_ALERTS: bool

# Registration
OSCAR_SEND_REGISTRATION_EMAIL: bool
OSCAR_FROM_EMAIL: str

# Slug handling
OSCAR_SLUG_FUNCTION: str
OSCAR_SLUG_MAP: dict[str, str]
OSCAR_SLUG_BLACKLIST: list[str]
OSCAR_SLUG_ALLOW_UNICODE: bool

# Cookies
OSCAR_COOKIES_DELETE_ON_LOGOUT: list[str]

# Offers
OSCAR_OFFERS_INCL_TAX: bool
OSCAR_OFFERS_IMPLEMENTED_TYPES: list[str]

# Hidden features
OSCAR_HIDDEN_FEATURES: list[str]

# Dashboard navigation
OSCAR_DASHBOARD_NAVIGATION: list[dict[str, Any]]
OSCAR_DASHBOARD_DEFAULT_ACCESS_FUNCTION: str

# Search facets
OSCAR_SEARCH_FACETS: dict[str, Any]

# Thumbnails
OSCAR_THUMBNAILER: str

# URL schema
OSCAR_URL_SCHEMA: str

# Email
OSCAR_SAVE_SENT_EMAILS_TO_DB: bool

# Catalogue
OSCAR_CATALOGUE_USE_POSTGRES_MATERIALISED_VIEWS: bool

# Haystack
HAYSTACK_SIGNAL_PROCESSOR: str
