from decimal import Decimal
from typing import Any

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from oscar.apps.checkout.session import CheckoutSessionMixin
from oscar.core.prices import Price

class OrderPlacementMixin(CheckoutSessionMixin):
    _payment_sources: list[Any] | None
    _payment_events: list[Any] | None
    view_signal: Any

    # Payment handling methods
    def handle_payment(self, order_number: str | int, total: Price, **kwargs: Any) -> None: ...
    def add_payment_source(self, source: Any) -> None: ...
    def add_payment_event(self, event_type_name: str, amount: Decimal, reference: str = ...) -> None: ...

    # Placing order methods
    def generate_order_number(self, basket: Any) -> str | int: ...
    def handle_order_placement(
        self,
        order_number: str | int,
        user: Any,
        basket: Any,
        shipping_address: Any,
        shipping_method: Any,
        shipping_charge: Price,
        billing_address: Any,
        order_total: Price,
        surcharges: Any | None = ...,
        **kwargs: Any,
    ) -> HttpResponse: ...
    def place_order(
        self,
        order_number: str | int,
        user: Any,
        basket: Any,
        shipping_address: Any,
        shipping_method: Any,
        shipping_charge: Price,
        order_total: Price,
        billing_address: Any | None = ...,
        surcharges: Any | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def create_shipping_address(self, user: Any, shipping_address: Any) -> Any | None: ...
    def update_address_book(self, user: Any, addr: Any) -> None: ...
    def create_billing_address(
        self, user: Any, billing_address: Any | None = ..., shipping_address: Any | None = ..., **kwargs: Any
    ) -> Any | None: ...
    def save_payment_details(self, order: Any) -> None: ...
    def save_payment_events(self, order: Any) -> None: ...
    def save_payment_sources(self, order: Any) -> None: ...
    def get_initial_order_status(self, basket: Any) -> str | None: ...

    # Post-order methods
    def handle_successful_order(self, order: Any) -> HttpResponseRedirect: ...
    def send_signal(self, request: HttpRequest, response: HttpResponse, order: Any) -> None: ...
    def get_success_url(self) -> str: ...
    def send_order_placed_email(self, order: Any) -> None: ...
    def get_message_context(self, order: Any) -> dict[str, Any]: ...

    # Basket helpers
    def get_submitted_basket(self) -> Any: ...
    def freeze_basket(self, basket: Any) -> None: ...
    def restore_frozen_basket(self) -> None: ...
