from typing import Any

from django.http import HttpRequest, HttpResponse
from oscar.apps.checkout.utils import CheckoutSessionData
from oscar.core.prices import Price

class CheckoutSessionMixin:
    pre_conditions: list[str] | None
    skip_conditions: list[str] | None
    checkout_session: CheckoutSessionData

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def check_pre_conditions(self, request: HttpRequest) -> None: ...
    def get_pre_conditions(self, request: HttpRequest) -> list[str]: ...
    def check_skip_conditions(self, request: HttpRequest) -> None: ...
    def get_skip_conditions(self, request: HttpRequest) -> list[str]: ...

    # Re-usable pre-condition validators
    def check_basket_is_not_empty(self, request: HttpRequest) -> None: ...
    def check_basket_is_valid(self, request: HttpRequest) -> None: ...
    def check_user_email_is_captured(self, request: HttpRequest) -> None: ...
    def check_shipping_data_is_captured(self, request: HttpRequest) -> None: ...
    def check_a_valid_shipping_address_is_captured(self) -> None: ...
    def check_a_valid_shipping_method_is_captured(self) -> None: ...
    def check_payment_data_is_captured(self, request: HttpRequest) -> None: ...

    # Re-usable skip conditions
    def skip_unless_basket_requires_shipping(self, request: HttpRequest) -> None: ...
    def skip_unless_payment_is_required(self, request: HttpRequest) -> None: ...

    # Helpers
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def build_submission(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_shipping_address(self, basket: Any) -> Any | None: ...
    def get_shipping_method(self, basket: Any, shipping_address: Any | None = ..., **kwargs: Any) -> Any | None: ...
    def get_billing_address(self, shipping_address: Any) -> Any | None: ...
    def get_order_totals(
        self, basket: Any, shipping_charge: Price, surcharges: Any | None = ..., **kwargs: Any
    ) -> Price: ...
