from typing import Any, ClassVar

from django.http import HttpRequest

class CheckoutSessionData:
    SESSION_KEY: ClassVar[str]
    request: HttpRequest

    def __init__(self, request: HttpRequest) -> None: ...
    def flush(self) -> None: ...

    # Guest checkout
    def set_guest_email(self, email: str) -> None: ...
    def get_guest_email(self) -> str | None: ...

    # Shipping address
    def reset_shipping_data(self) -> None: ...
    def ship_to_user_address(self, address: Any) -> None: ...
    def ship_to_new_address(self, address_fields: dict[str, Any]) -> None: ...
    def new_shipping_address_fields(self) -> dict[str, Any] | None: ...
    def shipping_user_address_id(self) -> int | None: ...
    def user_address_id(self) -> int | None: ...
    def is_shipping_address_set(self) -> bool: ...

    # Shipping method
    def use_free_shipping(self) -> None: ...
    def use_shipping_method(self, code: str) -> None: ...
    def shipping_method_code(self, basket: Any) -> str | None: ...
    def is_shipping_method_set(self, basket: Any) -> bool: ...

    # Billing address
    def bill_to_new_address(self, address_fields: dict[str, Any]) -> None: ...
    def bill_to_user_address(self, address: Any) -> None: ...
    def bill_to_shipping_address(self) -> None: ...
    def billing_address_same_as_shipping(self) -> None: ...
    def is_billing_address_same_as_shipping(self) -> bool: ...
    def billing_user_address_id(self) -> int | None: ...
    def new_billing_address_fields(self) -> dict[str, Any] | None: ...
    def is_billing_address_set(self) -> bool: ...

    # Payment methods
    def pay_by(self, method: str) -> None: ...
    def payment_method(self) -> str | None: ...

    # Submission methods
    def set_order_number(self, order_number: str) -> None: ...
    def get_order_number(self) -> str | None: ...
    def set_submitted_basket(self, basket: Any) -> None: ...
    def get_submitted_basket_id(self) -> int | None: ...
