from typing import Any, ClassVar

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views import generic
from oscar.apps.checkout.mixins import OrderPlacementMixin
from oscar.apps.checkout.session import CheckoutSessionMixin
from oscar.core.prices import Price

class IndexView(CheckoutSessionMixin, generic.FormView):
    template_name: str
    form_class: type
    success_url: str
    pre_conditions: ClassVar[list[str]]

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def get_success_response(self) -> HttpResponseRedirect: ...

class ShippingAddressView(CheckoutSessionMixin, generic.FormView):
    template_name: str
    form_class: type
    success_url: str
    pre_conditions: ClassVar[list[str]]
    skip_conditions: ClassVar[list[str]]

    def get_initial(self) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_available_addresses(self) -> Any: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def form_valid(self, form: Any) -> HttpResponse: ...

class UserAddressUpdateView(CheckoutSessionMixin, generic.UpdateView):
    template_name: str
    form_class: type
    success_url: str

    def get_queryset(self) -> Any: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class UserAddressDeleteView(CheckoutSessionMixin, generic.DeleteView):
    template_name: str
    success_url: str

    def get_queryset(self) -> Any: ...
    def get_success_url(self) -> str: ...

class ShippingMethodView(CheckoutSessionMixin, generic.FormView):
    template_name: str
    form_class: type
    pre_conditions: ClassVar[list[str]]
    success_url: str
    _methods: list[Any]

    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_available_shipping_methods(self) -> list[Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def form_invalid(self, form: Any) -> HttpResponse: ...
    def get_success_response(self) -> HttpResponseRedirect: ...

class PaymentMethodView(CheckoutSessionMixin, generic.TemplateView):
    pre_conditions: ClassVar[list[str]]
    skip_conditions: ClassVar[list[str]]
    success_url: str

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_success_response(self) -> HttpResponseRedirect: ...
    def get_success_url(self) -> str: ...

class PaymentDetailsView(OrderPlacementMixin, generic.TemplateView):
    template_name: str
    template_name_preview: str
    pre_conditions: ClassVar[list[str]]
    preview: bool

    def get_pre_conditions(self, request: HttpRequest) -> list[str]: ...
    def get_skip_conditions(self, request: HttpRequest) -> list[str]: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def handle_place_order_submission(self, request: HttpRequest) -> HttpResponse: ...
    def handle_payment_details_submission(self, request: HttpRequest) -> HttpResponse: ...
    def render_preview(self, request: HttpRequest, **kwargs: Any) -> HttpResponse: ...
    def render_payment_details(self, request: HttpRequest, **kwargs: Any) -> HttpResponse: ...
    def get_default_billing_address(self) -> Any | None: ...
    def submit(
        self,
        user: Any,
        basket: Any,
        shipping_address: Any,
        shipping_method: Any,
        shipping_charge: Price,
        billing_address: Any,
        order_total: Price,
        payment_kwargs: dict[str, Any] | None = ...,
        order_kwargs: dict[str, Any] | None = ...,
        surcharges: Any | None = ...,
    ) -> HttpResponse: ...
    def get_template_names(self) -> list[str]: ...

class ThankYouView(generic.DetailView):
    template_name: str
    context_object_name: str

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_object(self, queryset: Any | None = ...) -> Any | None: ...
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
