from oscar.apps.wishlists.abstract_models import (
    AbstractLine,
    AbstractWishList,
    AbstractWishListSharedEmail,
)

class WishList(AbstractWishList): ...
class Line(AbstractLine): ...
class WishListSharedEmail(AbstractWishListSharedEmail): ...
