class PaymentError(Exception): ...
class UserCancelled(PaymentError): ...
class TransactionDeclined(PaymentError): ...
class GatewayError(PaymentError): ...
class InvalidGatewayRequestError(PaymentError): ...
class InsufficientPaymentSources(PaymentError): ...

class RedirectRequired(PaymentError):
    url: str
    def __init__(self, url: str) -> None: ...

class UnableToTakePayment(PaymentError): ...
