from oscar.apps.payment.abstract_models import (
    AbstractBankcard,
    AbstractSource,
    AbstractSourceType,
    AbstractTransaction,
)

class Transaction(AbstractTransaction): ...
class Source(AbstractSource): ...
class SourceType(AbstractSourceType): ...
class Bankcard(AbstractBankcard): ...
