from typing import Any

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.views.generic.base import View

class PostActionMixin:
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class BulkEditMixin:
    action_param: str
    actions: list[str] | tuple[str, ...] | None
    checkbox_object_name: str | None

    def get_checkbox_object_name(self) -> str: ...
    def get_error_url(self, request: HttpRequest) -> str: ...
    def get_success_url(self, request: HttpRequest) -> str: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_objects(self, ids: list[int]) -> list[Any]: ...
    def get_object_dict(self, ids: list[int]) -> dict[int, Any]: ...

class ObjectLookupView(View):
    model: type

    def get_queryset(self) -> QuerySet[Any]: ...
    def format_object(self, obj: Any) -> dict[str, Any]: ...
    def initial_filter(self, qs: QuerySet[Any], value: str) -> QuerySet[Any]: ...
    def lookup_filter(self, qs: QuerySet[Any], term: str) -> QuerySet[Any]: ...
    def paginate(self, qs: QuerySet[Any], page: int, page_limit: int) -> tuple[QuerySet[Any], bool]: ...
    def get_args(self) -> tuple[str | None, str | None, int, int]: ...
    def get(self, request: HttpRequest) -> JsonResponse: ...
