from typing import Any

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.template.response import TemplateResponse
from django.utils.functional import _StrPromise
from django.views.generic.base import View

class AbstractBulkAction:
    label: str | _StrPromise

class BulkAction(AbstractBulkAction):
    def execute(self, request: HttpRequest, objects: QuerySet[Any]) -> None: ...

class IntermediateBulkAction(AbstractBulkAction):
    form_class: type | None
    template: str
    require_irreversible_confirmation: bool

    def get_context(self) -> dict[str, Any]: ...
    def execute(self, request: HttpRequest, objects: QuerySet[Any], form: Any) -> None: ...

class PostActionMixin:
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class BulkEditMixin:
    action_param: str
    select_across_param: str
    actions: dict[str, BulkAction] | list[str] | tuple[str, ...] | None
    checkbox_object_name: str | None

    def get_actions(self) -> dict[str, AbstractBulkAction | None]: ...
    def get_checkbox_object_name(self) -> str: ...
    def get_error_url(self, request: HttpRequest) -> str: ...
    def get_success_url(self, request: HttpRequest) -> str: ...
    def get_select_across_queryset(self) -> QuerySet[Any]: ...
    def get_selected_ids(self, request: HttpRequest) -> list[Any]: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_objects(self, ids: list[Any]) -> QuerySet[Any]: ...

class IntermediateBulkEditMixin(BulkEditMixin):
    intermediate_actions: dict[str, IntermediateBulkAction]
    bulk_intermediate_session_key: str
    bulk_intermediate_token_param: str
    bulk_intermediate_ttl_seconds: int
    max_bulk_intermediate_ids: int

    def get_intermediate_url(self, request: HttpRequest, action: str) -> str: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_bulk_intermediate_token(self, action: str, object_ids: list[Any]) -> str: ...
    def _handle_intermediate_action(
        self, request: HttpRequest, action: str, *args: Any, **kwargs: Any
    ) -> HttpResponse: ...

class IntermediateBulkActionView(View):
    intermediate_actions: dict[str, IntermediateBulkAction]
    bulk_intermediate_session_key: str
    bulk_intermediate_token_param: str
    bulk_intermediate_ttl_seconds: int
    _action: str | None
    _selected_ids: list[Any]
    _token: str | None

    def __init__(self, **kwargs: Any) -> None: ...
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_cancel_url(self) -> str: ...
    def get_success_url(self) -> str: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_form(self, data: Any = ...) -> Any: ...
    def get_context_data(self, form: Any = ..., **kwargs: Any) -> dict[str, Any]: ...
    def get_template_name(self) -> str: ...
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> TemplateResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_objects(self, form: Any) -> QuerySet[Any]: ...
    def execute_action(self, request: HttpRequest, form: Any) -> None: ...
    def _clear_session(self, request: HttpRequest) -> None: ...

class ObjectLookupView(View):
    model: type

    def get_queryset(self) -> QuerySet[Any]: ...
    def format_object(self, obj: Any) -> dict[str, Any]: ...
    def initial_filter(self, qs: QuerySet[Any], value: str) -> QuerySet[Any]: ...
    def lookup_filter(self, qs: QuerySet[Any], term: str) -> QuerySet[Any]: ...
    def paginate(self, qs: QuerySet[Any], page: int, page_limit: int) -> tuple[QuerySet[Any], bool]: ...
    def get_args(self) -> tuple[str | None, str | None, int, int]: ...
    def get(self, request: HttpRequest) -> JsonResponse: ...
