from django.contrib import admin
from treebeard.admin import TreeAdmin

class AttributeInline(admin.TabularInline): ...
class ProductRecommendationInline(admin.TabularInline): ...
class CategoryInline(admin.TabularInline): ...
class ProductAttributeInline(admin.TabularInline): ...
class ProductClassAdmin(admin.ModelAdmin): ...
class ProductAdmin(admin.ModelAdmin): ...
class ProductAttributeAdmin(admin.ModelAdmin): ...
class OptionAdmin(admin.ModelAdmin): ...
class ProductAttributeValueAdmin(admin.ModelAdmin): ...
class AttributeOptionInline(admin.TabularInline): ...
class AttributeOptionGroupAdmin(admin.ModelAdmin): ...
class CategoryAdmin(TreeAdmin): ...
