from typing import Any

from django.db import models
from django.db.models import Q
from treebeard.mp_tree import MP_NodeQuerySet

class AttributeFilter(dict[str, tuple[str | None, Any]]):
    def __init__(self, filter_kwargs: dict[str, Any]) -> None: ...
    def field_names(self) -> Any: ...
    def _selector(self, attribute_type: str) -> str: ...
    def _select_value(self, types: list[str], lookup: str | None, value: Any) -> Q: ...
    def fast_query(
        self,
        attribute_types: Any,
        queryset: models.QuerySet[Any],
    ) -> models.QuerySet[Any]: ...

class ProductQuerySet(models.QuerySet[Any]):
    def filter_by_attributes(self, **filter_kwargs: Any) -> ProductQuerySet: ...
    def base_queryset(self) -> ProductQuerySet: ...
    def browsable(self) -> ProductQuerySet: ...
    def public(self) -> ProductQuerySet: ...
    def browsable_dashboard(self) -> ProductQuerySet: ...
    def prefetch_browsable_categories(
        self,
        queryset: models.QuerySet[Any] | None = ...,
    ) -> ProductQuerySet: ...
    def prefetch_public_children(
        self,
        queryset: models.QuerySet[Any] | None = ...,
    ) -> ProductQuerySet: ...
    def prefetch_attribute_values(
        self,
        include_parent_children_attributes: bool = ...,
    ) -> ProductQuerySet: ...

class CategoryQuerySet(MP_NodeQuerySet):
    def browsable(self) -> CategoryQuerySet: ...
    def for_menu(self) -> CategoryQuerySet: ...
