from collections.abc import Iterator
from typing import Any, ClassVar
import builtins

from django.db import models
from django.utils.functional import cached_property

class QuerysetCache(dict[str, Any]):
    _queryset: models.QuerySet[Any] | list[Any]
    _queryset_iterator: Any
    def __init__(self, queryset: models.QuerySet[Any] | list[Any]) -> None: ...
    def queryset(self) -> models.QuerySet[Any] | list[Any]: ...
    def get(self, code: str, default: Any = ...) -> Any: ...  # type: ignore[override]

class AttributesQuerysetCache:
    product: Any
    def __init__(self, product: Any) -> None: ...
    @cached_property
    def attributes(self) -> QuerysetCache: ...
    @cached_property
    def attribute_values(self) -> QuerysetCache: ...
    def set_attributes(self, attributes: QuerysetCache) -> None: ...

class ProductAttributesContainer:
    RESERVED_ATTRIBUTES: ClassVar[builtins.set[str]]
    def __init__(self, product: Any) -> None: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> ProductAttributesContainer: ...
    def __getstate__(self) -> dict[str, Any]: ...
    def __setstate__(self, d: dict[str, Any]) -> None: ...
    @property
    def product(self) -> Any: ...
    @property
    def initialized(self) -> bool: ...
    @property
    def cache(self) -> AttributesQuerysetCache: ...
    def initialize(self) -> None: ...
    def invalidate(self) -> None: ...
    def refresh(self) -> None: ...
    def __getattribute__(self, name: str) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def set(self, name: str, value: Any, validate_identifier: bool = ...) -> None: ...
    def update(self, adict: dict[str, Any]) -> None: ...  # type: ignore[override]
    def validate_attributes(self) -> None: ...
    def get_values(self) -> models.QuerySet[Any] | list[Any]: ...
    def get_value_by_attribute(self, attribute: Any) -> Any: ...
    def get_all_attributes(self) -> models.QuerySet[Any] | list[Any]: ...
    def get_attribute_by_code(self, code: str) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def prepare_save(
        self,
    ) -> tuple[list[Any], list[Any], list[Any], builtins.set[str]]: ...
    def save(self) -> None: ...
