from typing import Any

from django.db import models
from django.dispatch import Signal
from django.http import HttpRequest, HttpResponse
from django.views import generic
from django.views.generic import DetailView
from oscar.apps.catalogue.abstract_models import AbstractProduct
from oscar.apps.customer.forms import ProductAlertForm

class ProductDetailView(DetailView):
    context_object_name: str | None
    view_signal: Signal
    template_folder: str
    enforce_paths: bool
    enforce_parent: bool

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def is_viewable(self, product: AbstractProduct, request: HttpRequest) -> bool: ...
    def get_object(self, queryset: models.QuerySet[Any] | None = ...) -> AbstractProduct: ...
    def redirect_if_necessary(self, current_path: str, product: AbstractProduct) -> HttpResponse | None: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_alert_status(self) -> bool: ...
    def get_alert_form(self) -> ProductAlertForm: ...
    def send_signal(self, request: HttpRequest, response: HttpResponse, product: AbstractProduct) -> None: ...
    def get_template_names(self) -> list[str]: ...

class CatalogueView(generic.View): ...
class ProductCategoryView(generic.View): ...
