from typing import Any

from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.template.response import TemplateResponse
from django.views.generic import TemplateView

class IndexView(TemplateView):
    def get_template_names(self) -> list[str]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_active_vouchers(self) -> QuerySet[Any]: ...
    def get_hourly_report(self, orders: QuerySet[Any], hours: int = ..., segments: int = ...) -> dict[str, Any]: ...
    def get_stats(self) -> dict[str, Any]: ...

class PopUpWindowMixin:
    @property
    def is_popup(self) -> str | None: ...
    @property
    def is_popup_var(self) -> str: ...
    def add_success_message(self, message: str) -> None: ...

class PopUpWindowCreateUpdateMixin(PopUpWindowMixin):
    @property
    def to_field(self) -> str | None: ...
    @property
    def to_field_var(self) -> str: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class PopUpWindowCreateMixin(PopUpWindowCreateUpdateMixin):
    def popup_response(self, obj: Any) -> TemplateResponse: ...

class PopUpWindowUpdateMixin(PopUpWindowCreateUpdateMixin):
    def popup_response(self, obj: Any) -> TemplateResponse: ...

class PopUpWindowDeleteMixin(PopUpWindowMixin):
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def delete(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class LoginView(auth_views.LoginView):
    template_name: str
    authentication_form: type[AuthenticationForm]
    login_redirect_url: str
    def get_success_url(self) -> str: ...
