from typing import Any
import logging

from django.contrib.auth.tokens import PasswordResetTokenGenerator

class CustomerDispatcher:
    REGISTRATION_EVENT_CODE: str
    PASSWORD_RESET_EVENT_CODE: str
    PASSWORD_CHANGED_EVENT_CODE: str
    EMAIL_CHANGED_EVENT_CODE: str

    dispatcher: Any

    def __init__(self, logger: logging.Logger | None = ..., mail_connection: Any = ...) -> None: ...
    def send_registration_email_for_user(self, user: Any, extra_context: dict[str, Any]) -> None: ...
    def send_password_reset_email_for_user(self, user: Any, extra_context: dict[str, Any]) -> None: ...
    def send_password_changed_email_for_user(self, user: Any, extra_context: dict[str, Any]) -> None: ...
    def send_email_changed_email_for_user(self, user: Any, extra_context: dict[str, Any]) -> None: ...

def get_password_reset_url(user: Any, token_generator: PasswordResetTokenGenerator = ...) -> str: ...
def normalise_email(email: str) -> str: ...
