from typing import Any

from django.contrib.auth.forms import PasswordChangeForm
from django.forms import Form
from django.http import HttpRequest, HttpResponse
from django.views import generic

class AccountSummaryView(generic.RedirectView):
    pattern_name: str
    permanent: bool

class AccountRegistrationView(generic.FormView):
    redirect_field_name: str
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_logged_in_redirect(self) -> str: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...

class AccountAuthView(generic.TemplateView):
    template_name: str
    login_prefix: str
    registration_prefix: str
    login_form_class: type[Form]
    registration_form_class: type[Form]
    redirect_field_name: str
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_login_form(self, bind_data: bool = ...) -> Any: ...
    def get_login_form_kwargs(self, bind_data: bool = ...) -> dict[str, Any]: ...
    def validate_login_form(self) -> HttpResponse: ...
    def get_login_success_message(self, form: Any) -> str: ...
    def get_login_success_url(self, form: Any) -> str: ...
    def get_registration_form(self, bind_data: bool = ...) -> Any: ...
    def get_registration_form_kwargs(self, bind_data: bool = ...) -> dict[str, Any]: ...
    def validate_registration_form(self) -> HttpResponse: ...
    def get_registration_success_message(self, form: Any) -> str: ...
    def get_registration_success_url(self, form: Any) -> str: ...

class LogoutView(generic.RedirectView):
    url: str
    permanent: bool
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class ProfileView(generic.TemplateView):
    template_name: str
    page_title: str
    active_tab: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_profile_fields(self, user: Any) -> list[dict[str, Any]]: ...
    def get_model_field_data(self, model_class: Any, field_name: str) -> dict[str, Any]: ...

class ProfileUpdateView(generic.FormView):
    template_name: str
    page_title: str
    active_tab: str
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def send_email_changed_email(self, old_user: Any, new_email: str) -> None: ...

class ProfileDeleteView(generic.FormView):
    template_name: str
    page_title: str
    active_tab: str
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...

class ChangePasswordView(generic.FormView):
    form_class: type[PasswordChangeForm]
    template_name: str
    page_title: str
    active_tab: str
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def send_password_changed_email(self) -> None: ...

class EmailHistoryView(generic.ListView):
    context_object_name: str | None
    template_name: str
    paginate_by: int
    page_title: str
    active_tab: str

class EmailDetailView(generic.DetailView):
    template_name: str
    context_object_name: str | None
    active_tab: str
    def get_object(self, queryset: Any = ...) -> Any: ...
    def get_page_title(self) -> str: ...

class OrderHistoryView(generic.ListView):
    context_object_name: str | None
    template_name: str
    paginate_by: int
    page_title: str
    active_tab: str
    form: Any
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_queryset(self) -> Any: ...
    def get_context_data(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...

class OrderDetailView(generic.DetailView):
    active_tab: str
    def get_template_names(self) -> list[str]: ...
    def get_page_title(self) -> str: ...
    def get_object(self, queryset: Any = ...) -> Any: ...
    def do_reorder(self, order: Any) -> None: ...

class OrderLineView(generic.DetailView):
    def get_object(self, queryset: Any = ...) -> Any: ...
    def do_reorder(self, line: Any) -> None: ...

class AnonymousOrderFormView(generic.FormView):
    template_name: str
    def form_valid(self, form: Any) -> HttpResponse: ...
    def get_success_url(self) -> str: ...

class AnonymousOrderDetailView(generic.DetailView):
    template_name: str
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class AddressListView(generic.ListView):
    context_object_name: str | None
    template_name: str
    paginate_by: int
    active_tab: str
    page_title: str

class AddressCreateView(generic.CreateView):
    template_name: str
    active_tab: str
    page_title: str
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class AddressUpdateView(generic.UpdateView):
    template_name: str
    active_tab: str
    page_title: str
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_queryset(self) -> Any: ...
    def get_success_url(self) -> str: ...

class AddressDeleteView(generic.DeleteView):
    template_name: str
    page_title: str
    active_tab: str
    context_object_name: str | None
    def get_queryset(self) -> Any: ...
    def get_success_url(self) -> str: ...

class AddressChangeStatusView(generic.RedirectView):
    permanent: bool
    def get(
        self,
        request: HttpRequest,
        *args: Any,
        pk: int | None = ...,
        action: str | None = ...,
        **kwargs: Any,
    ) -> HttpResponse: ...
