import factory

class ProductClassFactory(factory.django.DjangoModelFactory): ...
class ProductFactory(factory.django.DjangoModelFactory): ...
class CategoryFactory(factory.django.DjangoModelFactory): ...
class ProductCategoryFactory(factory.django.DjangoModelFactory): ...
class ProductAttributeFactory(factory.django.DjangoModelFactory): ...
class OptionFactory(factory.django.DjangoModelFactory): ...
class AttributeOptionFactory(factory.django.DjangoModelFactory): ...
class AttributeOptionGroupFactory(factory.django.DjangoModelFactory): ...
class ProductAttributeValueFactory(factory.django.DjangoModelFactory): ...
class ProductReviewFactory(factory.django.DjangoModelFactory): ...
class ProductImageFactory(factory.django.DjangoModelFactory): ...
