import factory

class RangeFactory(factory.django.DjangoModelFactory): ...
class BenefitFactory(factory.django.DjangoModelFactory): ...
class ConditionFactory(factory.django.DjangoModelFactory): ...
class ConditionalOfferFactory(factory.django.DjangoModelFactory): ...
