import factory

class BillingAddressFactory(factory.django.DjangoModelFactory): ...
class ShippingAddressFactory(factory.django.DjangoModelFactory): ...
class OrderDiscountFactory(factory.django.DjangoModelFactory): ...
class OrderFactory(factory.django.DjangoModelFactory): ...
class OrderLineFactory(factory.django.DjangoModelFactory): ...
class ShippingEventTypeFactory(factory.django.DjangoModelFactory): ...
class ShippingEventFactory(factory.django.DjangoModelFactory): ...
