import factory

class SourceTypeFactory(factory.django.DjangoModelFactory): ...
class SourceFactory(factory.django.DjangoModelFactory): ...
class TransactionFactory(factory.django.DjangoModelFactory): ...
