from datetime import datetime, timedelta
from decimal import Decimal
from typing import Any, ClassVar

from django.contrib.auth.models import User
from django.db import models
from django.db.models.expressions import Combinable
from oscar.apps.basket.managers import OpenBasketManager, SavedBasketManager
from oscar.apps.catalogue.abstract_models import AbstractOption, AbstractProduct
from oscar.apps.offer.abstract_models import AbstractConditionalOffer
from oscar.apps.partner.abstract_models import AbstractStockRecord
from oscar.apps.voucher.abstract_models import AbstractVoucher
from oscar.models.fields.slugfield import SlugField

class AbstractBasket(models.Model):
    # Status constants
    OPEN: ClassVar[str]
    MERGED: ClassVar[str]
    SAVED: ClassVar[str]
    FROZEN: ClassVar[str]
    SUBMITTED: ClassVar[str]
    STATUS_CHOICES: ClassVar[tuple[tuple[str, str], ...]]

    editable_statuses: ClassVar[tuple[str, ...]]

    # Fields
    owner: models.ForeignKey[User | Combinable, User | None]
    owner_id: int | None
    status: models.CharField[str | Combinable, str]
    vouchers: models.ManyToManyField[AbstractVoucher, AbstractVoucher]
    date_created: models.DateTimeField[str | datetime | Combinable, datetime]
    date_merged: models.DateTimeField[str | datetime | Combinable | None, datetime | None]
    date_submitted: models.DateTimeField[str | datetime | Combinable | None, datetime | None]

    # Managers
    objects: ClassVar[models.Manager[AbstractBasket]]
    open: ClassVar[OpenBasketManager]
    saved: ClassVar[SavedBasketManager]

    # Instance attributes set in __init__
    _lines: Any
    offer_applications: Any

    class Meta:
        abstract: ClassVar[bool]
        app_label: ClassVar[str]
        verbose_name: ClassVar[str]
        verbose_name_plural: ClassVar[str]

    # Strategy property
    @property
    def has_strategy(self) -> bool: ...
    strategy: Any

    # Line methods
    def all_lines(self) -> models.QuerySet[AbstractLine]: ...
    def max_allowed_quantity(self) -> tuple[int | None, int | None]: ...
    def is_quantity_allowed(self, qty: int, line: AbstractLine | None = ...) -> tuple[bool, str | None]: ...
    def basket_quantity(self, line: AbstractLine) -> int: ...

    # Manipulation methods
    def flush(self) -> None: ...
    def get_stock_info(self, product: AbstractProduct, options: list[dict[str, Any]]) -> Any: ...
    def add_product(
        self, product: AbstractProduct, quantity: int = ..., options: list[dict[str, Any]] | None = ...
    ) -> tuple[AbstractLine, bool]: ...
    add: Any
    def applied_offers(self) -> dict[int, AbstractConditionalOffer]: ...
    def reset_offer_applications(self) -> None: ...
    def merge_line(self, line: AbstractLine, add_quantities: bool = ...) -> None: ...
    def merge(self, basket: AbstractBasket, add_quantities: bool = ...) -> None: ...
    def freeze(self) -> None: ...
    def thaw(self) -> None: ...
    def submit(self) -> None: ...
    set_as_submitted: Any

    def is_shipping_required(self) -> bool: ...

    # Helper methods
    def _create_line_reference(
        self, product: AbstractProduct, stockrecord: AbstractStockRecord, options: list[dict[str, Any]]
    ) -> str: ...
    def _get_total(self, model_property: str) -> Decimal: ...

    # Properties
    @property
    def is_empty(self) -> bool: ...
    @property
    def is_tax_known(self) -> bool: ...
    @property
    def total_excl_tax(self) -> Decimal: ...
    @property
    def total_tax(self) -> Decimal: ...
    @property
    def total_incl_tax(self) -> Decimal: ...
    @property
    def total_incl_tax_excl_discounts(self) -> Decimal: ...
    @property
    def total_discount(self) -> Decimal: ...
    @property
    def offer_discounts(self) -> list[dict[str, Any]]: ...
    @property
    def voucher_discounts(self) -> list[dict[str, Any]]: ...
    @property
    def has_shipping_discounts(self) -> bool: ...
    @property
    def shipping_discounts(self) -> list[dict[str, Any]]: ...
    @property
    def post_order_actions(self) -> list[dict[str, Any]]: ...
    @property
    def grouped_voucher_discounts(self) -> list[dict[str, Any]]: ...
    @property
    def total_excl_tax_excl_discounts(self) -> Decimal: ...
    @property
    def num_lines(self) -> int: ...
    @property
    def num_items(self) -> int: ...
    @property
    def num_items_without_discount(self) -> int: ...
    @property
    def num_items_with_discount(self) -> int: ...
    @property
    def time_before_submit(self) -> timedelta | None: ...
    @property
    def time_since_creation(self) -> timedelta: ...
    @property
    def contains_a_voucher(self) -> bool: ...
    @property
    def is_submitted(self) -> bool: ...
    @property
    def can_be_edited(self) -> bool: ...
    @property
    def currency(self) -> str | None: ...

    # Query methods
    def contains_voucher(self, code: str) -> bool: ...
    def product_quantity(self, product: AbstractProduct) -> int: ...
    def line_quantity(
        self, product: AbstractProduct, stockrecord: AbstractStockRecord, options: list[dict[str, Any]] | None = ...
    ) -> int: ...
    def get_status_display(self) -> str: ...

class AbstractLine(models.Model):
    # Fields
    basket: models.ForeignKey[AbstractBasket | Combinable, AbstractBasket]
    basket_id: int
    line_reference: SlugField
    product: models.ForeignKey[AbstractProduct | Combinable, AbstractProduct]
    product_id: int
    stockrecord: models.ForeignKey[AbstractStockRecord | Combinable, AbstractStockRecord]
    stockrecord_id: int
    quantity: models.PositiveIntegerField[float | Combinable, int]
    price_currency: models.CharField[str | Combinable, str]
    price_excl_tax: models.DecimalField[str | Decimal | Combinable | None, Decimal | None]
    price_incl_tax: models.DecimalField[str | Decimal | Combinable | None, Decimal | None]
    tax_code: models.CharField[str | Combinable | None, str | None]
    date_created: models.DateTimeField[str | datetime | Combinable, datetime]
    date_updated: models.DateTimeField[str | datetime | Combinable, datetime]

    # Instance attributes set in __init__
    discounts: Any

    class Meta:
        abstract: ClassVar[bool]
        app_label: ClassVar[str]
        ordering: ClassVar[list[str]]
        unique_together: ClassVar[tuple[str, ...]]
        verbose_name: ClassVar[str]
        verbose_name_plural: ClassVar[str]

    def save(self, *args: Any, **kwargs: Any) -> None: ...

    # Offer methods
    def clear_discount(self) -> None: ...
    def discount(
        self,
        discount_value: Decimal,
        affected_quantity: int,
        incl_tax: bool = ...,
        offer: AbstractConditionalOffer | None = ...,
    ) -> None: ...
    def consume(self, quantity: int, offer: AbstractConditionalOffer | None = ...) -> None: ...
    def get_price_breakdown(self) -> list[tuple[Decimal, Decimal, int]]: ...

    # Offer discount helpers
    def has_offer_discount(self, offer: AbstractConditionalOffer) -> bool: ...
    def quantity_with_offer_discount(self, offer: AbstractConditionalOffer) -> int: ...
    def quantity_without_offer_discount(self, offer: AbstractConditionalOffer) -> int: ...
    def is_available_for_offer_discount(self, offer: AbstractConditionalOffer) -> bool: ...
    def quantity_available_for_offer(self, offer: AbstractConditionalOffer) -> int: ...

    # Properties
    @property
    def consumer(self) -> Any: ...
    @property
    def _tax_ratio(self) -> Decimal: ...
    @property
    def has_discount(self) -> bool: ...
    @property
    def quantity_with_discount(self) -> int: ...
    @property
    def quantity_without_discount(self) -> int: ...
    @property
    def discount_value(self) -> Decimal: ...
    @property
    def purchase_info(self) -> Any: ...
    @property
    def is_tax_known(self) -> bool: ...
    @property
    def unit_effective_price(self) -> Decimal: ...
    @property
    def unit_price_excl_tax(self) -> Decimal | None: ...
    @property
    def unit_price_incl_tax(self) -> Decimal | None: ...
    @property
    def unit_tax(self) -> Decimal | None: ...
    @property
    def line_price_excl_tax(self) -> Decimal | None: ...
    @property
    def line_price_excl_tax_incl_discounts(self) -> Decimal | None: ...
    @property
    def line_price_incl_tax_incl_discounts(self) -> Decimal | None: ...
    @property
    def line_tax(self) -> Decimal | None: ...
    @property
    def line_price_incl_tax(self) -> Decimal | None: ...
    @property
    def description(self) -> str: ...
    def get_warning(self) -> str | None: ...

class AbstractLineAttribute(models.Model):
    line: models.ForeignKey[AbstractLine | Combinable, AbstractLine]
    line_id: int
    option: models.ForeignKey[AbstractOption | Combinable, AbstractOption]
    option_id: int
    value: models.JSONField[Any, Any]

    class Meta:
        abstract: ClassVar[bool]
        app_label: ClassVar[str]
        verbose_name: ClassVar[str]
        verbose_name_plural: ClassVar[str]
