from typing import Any, ClassVar

from django import forms

class BasketLineForm(forms.ModelForm):
    quantity: forms.IntegerField
    save_for_later: forms.BooleanField

    def __init__(self, strategy: Any, *args: Any, **kwargs: Any) -> None: ...
    def full_clean(self) -> None: ...
    def has_changed(self) -> bool: ...
    def clean_quantity(self) -> int: ...
    def check_max_allowed_quantity(self, qty: int) -> None: ...
    def check_permission(self, qty: int) -> None: ...

    class Meta:
        model: type
        fields: list[str]

class SavedLineForm(forms.ModelForm):
    move_to_basket: forms.BooleanField
    strategy: Any
    basket: Any

    def __init__(self, strategy: Any, basket: Any, *args: Any, **kwargs: Any) -> None: ...
    def clean(self) -> dict[str, Any]: ...

    class Meta:
        model: type
        fields: tuple[str, ...]

class BasketVoucherForm(forms.Form):
    code: forms.CharField

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clean_code(self) -> str: ...

class AddToBasketForm(forms.Form):
    OPTION_FIELD_FACTORIES: ClassVar[dict[str, Any]]

    quantity: forms.IntegerField
    basket: Any
    parent_product: Any
    child_product: Any

    def __init__(self, basket: Any, product: Any, *args: Any, **kwargs: Any) -> None: ...
    def _create_parent_product_fields(self, product: Any) -> None: ...
    def _create_product_fields(self, product: Any) -> None: ...
    def _add_option_field(self, product: Any, option: Any) -> None: ...
    def clean_child_id(self) -> str: ...
    def clean_quantity(self) -> int: ...
    @property
    def product(self) -> Any: ...
    def clean(self) -> dict[str, Any]: ...
    def cleaned_options(self) -> list[dict[str, Any]]: ...

class SimpleAddToBasketMixin:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class SimpleAddToBasketForm(SimpleAddToBasketMixin, AddToBasketForm): ...
