from typing import Any, ClassVar

from django.db import models

class OpenBasketManager(models.Manager):
    status_filter: ClassVar[str]
    def get_queryset(self) -> models.QuerySet: ...
    def get_or_create(self, **kwargs: Any) -> tuple[Any, bool]: ...

class SavedBasketManager(models.Manager):
    status_filter: ClassVar[str]
    def get_queryset(self) -> models.QuerySet: ...
    def create(self, **kwargs: Any) -> Any: ...
    def get_or_create(self, **kwargs: Any) -> tuple[Any, bool]: ...
