from collections.abc import Callable

from django.http import HttpRequest, HttpResponse
from django.template.response import TemplateResponse
from oscar.apps.basket.abstract_models import AbstractBasket
from oscar.apps.basket.managers import OpenBasketManager

class BasketMiddleware:
    get_response: Callable[[HttpRequest], HttpResponse]
    def __init__(self, get_response: Callable[[HttpRequest], HttpResponse]) -> None: ...
    def __call__(self, request: HttpRequest) -> HttpResponse: ...
    def process_response(self, request: HttpRequest, response: HttpResponse) -> HttpResponse: ...
    def get_cookie_key(self, request: HttpRequest) -> str: ...
    def process_template_response(self, request: HttpRequest, response: TemplateResponse) -> TemplateResponse: ...
    def get_basket(self, request: HttpRequest) -> AbstractBasket: ...
    def merge_baskets(self, master: AbstractBasket, slave: AbstractBasket) -> None: ...
    def get_cookie_basket(
        self, cookie_key: str, request: HttpRequest, manager: OpenBasketManager
    ) -> AbstractBasket | None: ...
    def apply_offers_to_basket(self, request: HttpRequest, basket: AbstractBasket) -> None: ...
    def get_basket_hash(self, basket_id: int) -> str: ...
