from collections.abc import Iterator
from typing import Any, NamedTuple

from django.http import HttpRequest

class DiscountApplication(NamedTuple):
    amount: Any
    quantity: int
    incl_tax: bool
    offer: Any

class BasketMessageGenerator:
    new_total_template_name: str
    offer_lost_template_name: str
    offer_gained_template_name: str

    def get_new_total_messages(self, basket: Any, include_buttons: bool = ...) -> list[tuple[int, str]]: ...
    def get_offer_lost_messages(
        self, offers_before: dict[int, Any], offers_after: dict[int, Any]
    ) -> list[tuple[int, str]]: ...
    def get_offer_gained_messages(
        self, offers_before: dict[int, Any], offers_after: dict[int, Any]
    ) -> list[tuple[int, str]]: ...
    def get_offer_messages(
        self, offers_before: dict[int, Any], offers_after: dict[int, Any]
    ) -> list[tuple[int, str]]: ...
    def get_messages(
        self,
        basket: Any,
        offers_before: dict[int, Any],
        offers_after: dict[int, Any],
        include_buttons: bool = ...,
    ) -> list[tuple[int, str]]: ...
    def apply_messages(self, request: HttpRequest, offers_before: dict[int, Any]) -> None: ...

class LineOfferConsumer:
    def __init__(self, line: Any) -> None: ...
    def consume(self, quantity: int, offer: Any | None = ...) -> int: ...
    def consumed(self, offer: Any | None = ...) -> int: ...
    def num_consumed(self, offer: Any | None = ...) -> int: ...
    @property
    def consumers(self) -> list[Any]: ...
    def available(self, offer: Any | None = ...) -> int: ...

class LineDiscountRegistry(LineOfferConsumer):
    def __init__(self, line: Any) -> None: ...
    def discount(
        self,
        amount: Any,
        quantity: int,
        incl_tax: bool = ...,
        offer: Any | None = ...,
    ) -> None: ...
    @property
    def excl_tax(self) -> Any: ...
    @property
    def incl_tax(self) -> Any: ...
    @property
    def total(self) -> Any: ...
    def all(self) -> list[DiscountApplication]: ...
    def __iter__(self) -> Iterator[DiscountApplication]: ...
