from typing import Any
import datetime

from django.db.models import QuerySet
from django.http import HttpResponse

class ReportGenerator:
    filename_template: str
    content_type: str
    code: str
    description: str
    date_range_field_name: str | None
    model_class: type | None
    queryset: QuerySet[Any] | None
    start_date: datetime.date | None
    end_date: datetime.date | None
    formatter: ReportFormatter

    def __init__(self, **kwargs: Any) -> None: ...
    def report_description(self) -> str: ...
    def get_queryset(self) -> QuerySet[Any]: ...
    def generate(self) -> HttpResponse | QuerySet[Any]: ...
    def filename(self) -> str: ...
    def is_available_to(self, user: Any) -> bool: ...
    def filter_with_date_range(self, queryset: QuerySet[Any]) -> QuerySet[Any]: ...

class ReportFormatter:
    def format_datetime(self, dt: datetime.datetime | None) -> str: ...
    def format_date(self, d: datetime.date | None) -> str: ...
    def format_timedelta(self, td: datetime.timedelta) -> str: ...
    def filename(self) -> str: ...

class ReportCSVFormatter(ReportFormatter):
    def get_csv_writer(self, file_handle: Any, **kwargs: Any) -> Any: ...
    def generate_response(self, objects: QuerySet[Any], **kwargs: Any) -> HttpResponse: ...

class ReportHTMLFormatter(ReportFormatter):
    def generate_response(self, objects: QuerySet[Any], **kwargs: Any) -> QuerySet[Any]: ...
