class InvalidStatus(Exception): ...
class InvalidOrderStatus(InvalidStatus): ...
class InvalidLineStatus(InvalidStatus): ...
class InvalidShippingEvent(Exception): ...
class InvalidPaymentEvent(Exception): ...
class UnableToPlaceOrder(Exception): ...
