from typing import Any

from django import forms

class CommunicationEventTypeForm(forms.ModelForm):
    email_subject_template: forms.CharField
    email_body_template: forms.CharField
    email_body_html_template: forms.CharField
    preview_order_number: forms.CharField
    preview_email: forms.EmailField
    show_preview: bool
    send_preview: bool

    def __init__(self, *args: Any, data: Any = ..., **kwargs: Any) -> None: ...
    def validate_template(self, value: str) -> None: ...
    def clean_email_subject_template(self) -> str: ...
    def clean_email_body_template(self) -> str: ...
    def clean_email_body_html_template(self) -> str: ...
    def clean_preview_order_number(self) -> str: ...
    def clean_preview_email(self) -> str: ...
    def get_preview_context(self) -> dict[str, Any]: ...

    class Meta:
        model: type
        fields: list[str]
