from typing import Any

class PhoneNumberMixin:
    country: Any
    region_code: str | None
    phone_number_fields: dict[str, dict[str, Any]]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_country(self) -> Any: ...
    def set_country_and_region_code(self) -> None: ...
    def clean_phone_number_field(self, field_name: str) -> Any: ...
    def clean(self) -> dict[str, Any]: ...
