from typing import Any

from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic import FormView

class OfferWizardStepView(FormView):
    wizard_name: str
    form_class: type | None
    step_name: str | None
    update: bool
    url_name: str | None
    success_url_name: str
    previous_view: type | None
    offer: Any

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def is_previous_step_complete(self, request: HttpRequest) -> bool: ...
    def get_form_kwargs(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_title(self) -> str: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def save_offer(self, offer: Any) -> HttpResponseRedirect: ...
    def get_success_url(self) -> str: ...
    @classmethod
    def is_valid(cls, current_view: OfferWizardStepView, request: HttpRequest) -> bool: ...
