from typing import Any

from django.db.models.fields import CharField, DecimalField
from oscar.models.fields.autoslugfield import AutoSlugField as AutoSlugField
from phonenumber_field.modelfields import PhoneNumberField as PhoneNumberField

class Creator:
    field: Any
    def __init__(self, field: Any) -> None: ...
    def __get__(self, obj: Any, type: type | None = ...) -> Any: ...
    def __set__(self, obj: Any, value: Any) -> None: ...

class ExtendedURLField(CharField):
    description: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def formfield(self, **kwargs: Any) -> Any: ...
    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]: ...

class PositiveDecimalField(DecimalField):
    def formfield(self, **kwargs: Any) -> Any: ...

class UppercaseCharField(CharField):
    def contribute_to_class(self, cls: type, name: str, private_only: bool = ..., **kwargs: Any) -> None: ...
    def from_db_value(self, value: Any, *args: Any, **kwargs: Any) -> Any: ...
    def to_python(self, value: Any) -> str | None: ...

class NullCharField(CharField):
    description: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def contribute_to_class(self, cls: type, name: str, private_only: bool = ..., **kwargs: Any) -> None: ...
    def from_db_value(self, value: Any, *args: Any, **kwargs: Any) -> str: ...
    def get_prep_value(self, value: Any) -> str | None: ...
    def deconstruct(self) -> tuple[str, str, list[Any], dict[str, Any]]: ...
