from typing import Any

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic import DetailView, FormView, ListView, UpdateView
from oscar.views.generic import BulkEditMixin

def queryset_orders_for_user(user: Any) -> QuerySet[Any]: ...
def get_order_for_user_or_404(user: Any, number: str) -> Any: ...

class OrderStatsView(FormView):
    template_name: str
    form_class: type
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def get_form_kwargs(self) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_stats(self, filters: dict[str, Any]) -> dict[str, Any]: ...

class OrderListView(BulkEditMixin, ListView):
    context_object_name: str
    template_name: str
    form_class: type
    paginate_by: int
    actions: tuple[str, ...]
    CSV_COLUMNS: dict[str, str]
    base_queryset: QuerySet[Any]
    form: Any
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_search_filter_descriptions(self) -> list[str]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def is_csv_download(self) -> bool: ...
    def get_paginate_by(self, queryset: QuerySet[Any]) -> int | None: ...
    def render_to_response(self, context: dict[str, Any], **response_kwargs: Any) -> HttpResponse: ...
    def get_download_filename(self, request: HttpRequest) -> str: ...
    def get_row_values(self, order: Any) -> dict[str, Any]: ...
    def download_selected_orders(self, request: HttpRequest, orders: QuerySet[Any]) -> HttpResponse: ...
    def change_order_statuses(self, request: HttpRequest, orders: QuerySet[Any]) -> HttpResponse: ...
    def change_order_status(self, request: HttpRequest, order: Any) -> None: ...

class OrderDetailView(DetailView):
    context_object_name: str
    template_name: str
    order_actions: tuple[str, ...]
    line_actions: tuple[str, ...]
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_order_lines(self) -> QuerySet[Any]: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def handle_order_action(self, request: HttpRequest, order: Any, action: str) -> HttpResponse: ...
    def handle_line_action(self, request: HttpRequest, order: Any, action: str) -> HttpResponse: ...
    def reload_page(self, fragment: str | None = ..., error: str | None = ...) -> HttpResponseRedirect: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_payment_transactions(self) -> QuerySet[Any]: ...
    def get_order_note_form(self) -> Any: ...
    def get_order_status_form(self) -> Any: ...
    def save_note(self, request: HttpRequest, order: Any) -> HttpResponse: ...
    def delete_note(self, request: HttpRequest, order: Any) -> HttpResponseRedirect: ...
    def change_order_status(self, request: HttpRequest, order: Any) -> HttpResponseRedirect: ...
    def create_order_payment_event(self, request: HttpRequest, order: Any) -> HttpResponseRedirect: ...
    def change_line_statuses(
        self, request: HttpRequest, order: Any, lines: QuerySet[Any], quantities: list[int]
    ) -> HttpResponseRedirect: ...
    def create_shipping_event(
        self, request: HttpRequest, order: Any, lines: QuerySet[Any], quantities: list[int]
    ) -> HttpResponseRedirect: ...
    def create_payment_event(
        self, request: HttpRequest, order: Any, lines: QuerySet[Any], quantities: list[int]
    ) -> HttpResponseRedirect: ...

class LineDetailView(DetailView):
    context_object_name: str
    template_name: str
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

def get_changes_between_models(
    model1: Any, model2: Any, excludes: list[str] | None = ...
) -> dict[str, tuple[Any, Any]]: ...
def get_change_summary(model1: Any, model2: Any) -> str: ...

class ShippingAddressUpdateView(UpdateView):
    context_object_name: str
    template_name: str
    form_class: type
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Any: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def get_success_url(self) -> str: ...
