from typing import Any

from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.views import generic

class VoucherListView(generic.ListView):
    context_object_name: str
    template_name: str
    form_class: type
    paginate_by: int
    form: Any
    advanced_form: Any
    search_filters: list[str]
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class VoucherCreateView(generic.CreateView):
    template_name: str
    form_class: type
    success_url: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_initial(self) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def get_success_url(self) -> str: ...

class VoucherStatsView(generic.DetailView):
    template_name: str
    context_object_name: str
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class VoucherUpdateView(generic.UpdateView):
    template_name: str
    context_object_name: str
    form_class: type
    success_url: str
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_initial(self) -> dict[str, Any]: ...
    def form_valid(self, form: Any) -> HttpResponse: ...
    def get_success_url(self) -> str: ...

class VoucherDeleteView(generic.DeleteView):
    template_name: str
    context_object_name: str
    def delete(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_success_url(self) -> str: ...

class VoucherSetCreateView(generic.CreateView):
    template_name: str
    form_class: type
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_initial(self) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class VoucherSetUpdateView(generic.UpdateView):
    template_name: str
    context_object_name: str
    form_class: type
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_initial(self) -> dict[str, Any]: ...
    def get_success_url(self) -> str: ...

class VoucherSetDetailView(generic.ListView):
    context_object_name: str
    template_name: str
    form_class: type
    paginate_by: int
    voucher_set: Any
    form: Any
    search_filters: list[str]
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class VoucherSetListView(generic.ListView):
    context_object_name: str
    template_name: str
    paginate_by: int
    def get_queryset(self) -> QuerySet[Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class VoucherSetDownloadView(generic.DetailView):
    template_name: str
    form_class: type
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse: ...

class VoucherSetDeleteView(generic.DeleteView):
    template_name: str
    context_object_name: str
    def get_success_url(self) -> str: ...
