import logging

from oscar.core.application import OscarConfig

def create_local_app_folder(local_app_path: str) -> None: ...
def subfolders(path: str) -> list[str]: ...
def inherit_app_config(local_app_folder_path: str, local_app_name: str, app_config: OscarConfig) -> None: ...
def fork_app(
    label: str,
    local_folder_path: str,
    local_app_subpackage: str | None = ...,
    logger: logging.Logger | None = ...,
) -> None: ...
def create_file(filepath: str, content: str = ...) -> None: ...
