from collections.abc import Sequence
from types import ModuleType
from typing import Any

from django.db import models

MOVED_MODELS: dict[str, tuple[str, list[str]]]

def get_class(module_label: str, classname: str, module_prefix: str = ...) -> type: ...
def get_class_loader() -> Any: ...
def get_classes(module_label: str, classnames: Sequence[str], module_prefix: str = ...) -> list[type]: ...
def default_class_loader(module_label: str, classnames: Sequence[str], module_prefix: str) -> list[type]: ...
def _import_module(module_label: str, classnames: Sequence[str]) -> ModuleType | None: ...
def _pluck_classes(modules: list[ModuleType | None], classnames: Sequence[str]) -> list[type]: ...
def _find_registered_app_name(module_label: str) -> str: ...
def get_model(app_label: str, model_name: str) -> type[models.Model]: ...
def is_model_registered(app_label: str, model_name: str) -> bool: ...
def get_profile_class() -> type[models.Model] | None: ...
def feature_hidden(feature_name: str | None) -> bool: ...
def cached_import_string(path: str) -> Any: ...
