from typing import Any

class AbstractThumbnailer:
    def generate_thumbnail(self, source: Any, **opts: Any) -> Any: ...
    def delete_thumbnails(self, source: Any) -> None: ...

class SorlThumbnail(AbstractThumbnailer):
    def __init__(self) -> None: ...
    def generate_thumbnail(self, source: Any, **opts: Any) -> Any: ...
    def delete_thumbnails(self, source: Any) -> None: ...

class EasyThumbnails(AbstractThumbnailer):
    def __init__(self) -> None: ...
    def generate_thumbnail(self, source: Any, **opts: Any) -> Any: ...
    def delete_thumbnails(self, source: Any) -> None: ...

def get_thumbnailer() -> AbstractThumbnailer: ...
