from decimal import Decimal
import datetime
import re

from django.http import HttpRequest, HttpResponseRedirect

SLUGIFY_RE: re.Pattern[str]

def cautious_slugify(value: str) -> str: ...
def default_slugifier(value: str, allow_unicode: bool = ...) -> str: ...
def slugify(value: str) -> str: ...
def format_timedelta(td: datetime.timedelta) -> str: ...
def format_datetime(dt: datetime.datetime, dt_format: str | None = ...) -> str: ...
def datetime_combine(date: datetime.date, time: datetime.time) -> datetime.datetime: ...
def safe_referrer(request: HttpRequest, default: str | None) -> str | None: ...
def redirect_to_referrer(request: HttpRequest, default: str | None) -> HttpResponseRedirect: ...
def get_default_currency() -> str: ...
def round_half_up_two_dec(money: Decimal) -> Decimal: ...
def round_half_up(money: Decimal) -> Decimal: ...
def round_half_up_four_dec(money: Decimal) -> Decimal: ...
def is_ajax(request: HttpRequest) -> bool: ...
