from django.core import validators

class ExtendedURLValidator(validators.URLValidator):
    is_local_url: bool
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __call__(self, value: str) -> None: ...
    def _validate_url(self, value: str) -> None: ...
    def validate_local_url(self, value: str) -> None: ...
    def clean_url(self, value: str) -> str: ...

class URLDoesNotExistValidator(ExtendedURLValidator):
    def __call__(self, value: str) -> None: ...

def non_whitespace(value: str) -> str: ...
def non_python_keyword(value: str) -> str: ...
