from typing import Any

from oscar.apps.shipping.methods import Base

class Repository:
    methods: tuple[Base, ...]

    def get_shipping_methods(self, basket: Any, shipping_addr: Any | None = ..., **kwargs: Any) -> list[Base]: ...
    def get_default_shipping_method(self, basket: Any, shipping_addr: Any | None = ..., **kwargs: Any) -> Base: ...
    def get_available_shipping_methods(
        self, basket: Any, shipping_addr: Any | None = ..., **kwargs: Any
    ) -> tuple[Base, ...] | list[Base]: ...
    def apply_shipping_offers(self, basket: Any, methods: list[Base]) -> list[Base]: ...
    def apply_shipping_offer(self, basket: Any, method: Base, offer: Any) -> Base: ...
