from typing import Any

from django.db.models.query import QuerySet
from django.http import HttpRequest

class OfferApplicationError(Exception): ...

class Applicator:
    def apply(self, basket: Any, user: Any | None = ..., request: HttpRequest | None = ...) -> None: ...
    def apply_offers(self, basket: Any, offers: list[Any]) -> None: ...
    def get_offers(self, basket: Any, user: Any | None = ..., request: HttpRequest | None = ...) -> list[Any]: ...
    def get_site_offers(self) -> QuerySet[Any]: ...
    def get_basket_offers(self, basket: Any, user: Any | None) -> list[Any]: ...
    def get_user_offers(self, user: Any | None) -> QuerySet[Any] | list[Any]: ...
    def get_session_offers(self, request: Any | None) -> list[Any]: ...
