from typing import Any

from django.db.models.query import QuerySet
from django.http import HttpRequest
from oscar.apps.basket.abstract_models import AbstractBasket
from oscar.apps.offer.abstract_models import AbstractConditionalOffer

class OfferApplicationError(Exception): ...

class Applicator:
    def apply(self, basket: AbstractBasket, user: Any | None = ..., request: HttpRequest | None = ...) -> None: ...
    def apply_offers(self, basket: AbstractBasket, offers: list[AbstractConditionalOffer]) -> None: ...
    def get_offers(
        self, basket: AbstractBasket, user: Any | None = ..., request: HttpRequest | None = ...
    ) -> list[AbstractConditionalOffer]: ...
    def get_site_offers(self) -> QuerySet[AbstractConditionalOffer]: ...
    def get_basket_offers(self, basket: AbstractBasket, user: Any | None) -> list[AbstractConditionalOffer]: ...
    def get_user_offers(self, user: Any | None) -> list[AbstractConditionalOffer]: ...
    def get_session_offers(self, request: HttpRequest | None) -> list[AbstractConditionalOffer]: ...
