from decimal import Decimal
from typing import Any

from django.utils.functional import _StrPromise
from oscar.apps.offer.models import Condition

__all__: list[str] = ["CountCondition", "CoverageCondition", "ValueCondition"]

class CountCondition(Condition):
    @property
    def name(self) -> str | _StrPromise: ...
    @property
    def description(self) -> str | _StrPromise: ...
    def is_satisfied(self, offer: Any, basket: Any) -> bool: ...
    def is_partially_satisfied(self, offer: Any, basket: Any) -> bool: ...
    def get_upsell_message(self, offer: Any, basket: Any) -> str | None: ...
    def consume_items(self, offer: Any, basket: Any, affected_lines: list[Any]) -> None: ...

class CoverageCondition(Condition):
    @property
    def name(self) -> str | _StrPromise: ...
    @property
    def description(self) -> str | _StrPromise: ...
    def is_satisfied(self, offer: Any, basket: Any) -> bool: ...
    def is_partially_satisfied(self, offer: Any, basket: Any) -> bool: ...
    def get_upsell_message(self, offer: Any, basket: Any) -> str | None: ...
    def consume_items(self, offer: Any, basket: Any, affected_lines: list[Any]) -> None: ...
    def get_value_of_satisfying_items(self, offer: Any, basket: Any) -> Decimal: ...

class ValueCondition(Condition):
    @property
    def name(self) -> str | _StrPromise: ...
    @property
    def description(self) -> str | _StrPromise: ...
    def is_satisfied(self, offer: Any, basket: Any) -> bool: ...
    def is_partially_satisfied(self, offer: Any, basket: Any) -> bool: ...
    def get_upsell_message(self, offer: Any, basket: Any) -> str | _StrPromise | None: ...
    def consume_items(self, offer: Any, basket: Any, affected_lines: list[Any]) -> None: ...
