from decimal import Decimal
from typing import Any

from oscar.apps.offer.applicator import Applicator as Applicator

def range_anchor(product_range: Any) -> str: ...
def unit_price(offer: Any, line: Any) -> Decimal | None: ...
def load_proxy(proxy_class: str) -> type: ...
